### ISSUE TITLE
Generate gender from name

### ISSUE THREAD

**Issue by Shubham5798** [Shubham5798/api_example#2]
Write the code to predict whether the name is male or female

**Comment by ShubhamVarankar** [comment]
`import requests

name = input("Enter name: ")

url = "https://api.genderize.io?name=scott"

payload={'name': name}
files=[

]
headers = {}

response = requests.request("GET", url, headers=headers, data=payload, files=files)

print(response.text.split('"')[7])`

**Comment by ShubhamVarankar** [comment]
done

**Comment by Divya333** [comment]
assign this to me

**Comment by Shubham5798** [comment]
The issue has been addressed, thanks
